### ISSUE TITLE
NBT filtering for ingredients not working

### ISSUE THREAD

**Issue by chuckomuffin** [LoreSchaeffer/NBTRecipes#1]
While I am able to craft items with NBT data successfully, when I specify NBT data for the ingredients that requirement is ignored.

Example:

﻿{
    "type": "crafting_shapeless",
    "ingredients": [
        {
            "material": "minecraft:item_frame",
            "name": "&rCubit Horde",
            "nbt": "{CustomModelData: 111000}",
            "amount": 1
          }
    ],
    "result":       {
      "material": "minecraft:nautilus_shell",
      "name": "&rCube",
      "nbt": "{CustomModelData: 111111}",
      "amount": 9
    }
  }

I am able to use any item frame for this recipe, not just those with either the specified name or CustomModelData.

**Comment by LoreSchaeffer** [comment]
Thank you for the report, i'm trying to fix this week
