### ISSUE TITLE
new smithing table recipes

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [LoreSchaeffer/NBTRecipes#4]
I'm not sure if you updated this pack for that or not so I'm making this just to be sure

**Comment by LoreSchaeffer** [comment]
Yes, I haven't had time to update it yet. If you want to do it you can make a pull request. Thank you

**Comment by LoreSchaeffer** [comment]
Added support for new smithing templates, you can find the new release on spigot or modrinth.
