### ISSUE TITLE
Recipe Book Support

### ISSUE THREAD

**Issue by OakLoaf** [LoreSchaeffer/NBTRecipes#5]
It would be nice to be able to have recipes appear in the recipe book. Being able to define how they are given to the user would be nice too but just basic support would also be fine

**Comment by LoreSchaeffer** [comment]
The recipes are already present in the recipe book but you have to grant them for your player 
![image](https://github.com/LoreSchaeffer/NBTRecipes/assets/15457448/14750257-bc28-4f00-8db2-ae4abf13e140)
You can grant them with a plugin or with the command ```recipe give PLAYER RECIPE```.

**Comment by OakLoaf** [comment]
Makes sense, could also make a good feature for the plugin though!

**Comment by LoreSchaeffer** [comment]
Yes, i'll try to add this feature in a new version of the plugin

**Comment by LoreSchaeffer** [comment]
I've put a new release on modrinth and spigot with a first version of your feature

**Comment by OakLoaf** [comment]
I tested it out but am getting an error:
```
[20:12:34 WARN]: §eLoading of recipe glass_item_frame.json failed with error: com.google.gson.stream.MalformedJsonException: Unterminated object at line 25 column 4 path $.result
```

The recipe in question: https://smrt-1.com/pastes/J2flElL

**Comment by LoreSchaeffer** [comment]
You have an error in you json. You are missing a comma before the discover tag

**Comment by OakLoaf** [comment]
Oooh, thank you

________________________________
